server:
  port: ${SERVER_PORT:8080}
spring:
  application:
    name: techgarden-blog
  datasource:
    url: jdbc:postgresql://${PG_HOSTNAME}:${PG_PORT:5432}/${PG_DB:blog}
    username: ${PG_USER}
    password: ${PG_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jackson:
    serialization:
      write-dates-as-timestamps: false
  jpa:
    properties:
      hibernate.jdbc.time_zone: UTC
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}
management:
  endpoints:
    web:
      exposure:
        include: health,info