server:
  port: ${SERVER_PORT:8080}
spring:
  application:
    name: techgarden-blog
  datasource:
    url: jdbc:postgresql://${PG_HOSTNAME}:${PG_PORT:5432}/${PG_DB:blog}
    username: ${PG_USER}
    password: ${PG_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jackson:
    serialization:
      write-dates-as-timestamps: false
  jpa:
    properties:
      hibernate.jdbc.time_zone: UTC
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI}
        registration:
          svc-blog:
            provider: keycloak
            client-id: svc.blog
            client-secret: ${CLIENT_SECRET}
            authorization-grant-type: client_credentials
            redirect-uri: "{baseUrl}/api/login/oauth2/code/{registrationId}"
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}
management:
  endpoints:
    web:
      exposure:
        include: health,info
KEYCLOAK_ISSUER_URI: https://sso.dev.techgarden.gg/realms/techgarden