server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/blog
    username: myuser
    password: secret
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    org.springframework.security: DEBUG